---
name: Lint Code
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Check code with ruff
        uses: chartboost/ruff-action@v1
        with:
          version: 0.11.4
          args: check
          src: "."
